### ISSUE TITLE
web based link authentification : not working 

### ISSUE THREAD

**Issue by hafx** [mautrix/facebook#221]
Hi, 

I would like to use the web-based authentification. 
I enabled the public endpoints. It was working before I migrate my vm from debian to ubuntu 20.04.

**_My config_** 
```
# Public part of web server for out-of-Matrix interaction with the bridge.
    public:
        # Whether or not the public-facing endpoints should be enabled.
        enabled: true
        # The prefix to use in the public-facing endpoints.
        prefix: /public
        # The base URL where the public-facing endpoints are available. The prefix is not added
        # implicitly.
        external: https://192.168.0.5/public
        # Shared secret for integration managers such as mautrix-manager.
        # If set to "generate", a random string will be generated on the next startup.
        # If null, integration manager access to the API will not be possible.
        shared_secret: generate
        # Allow logging in within Matrix. If false, users can only log in using the web interface.
        allow_matrix_login: false
```
'https://docs.mau.fi/bridges/python/setup/index.html?bridge=facebook'
I am using systemd. 

**_The issue_** 
Nothing is listening on 443 (using netstat) in my vm like nginx (or other). 
The bridge is working but I can't use the link generated by the instance. (for the web-based auth)
What am I supposed to do ?

any idea ?

Thanks
